name: giskard

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  zeroth:
    name: zeroth
    runs-on: ubuntu-latest

    steps:
      - name: Checkout zeroth
        uses: actions/checkout@v4

      - name: zeroth
        uses: Malstrom/giskard@main
        with:
          repo: .
          mode: zeroth
          github-token: ${{ secrets.GITHUB_TOKEN }}
