name: giskard

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  zeroth-dojo:
    name: zeroth@dojo
    runs-on: ubuntu-latest

    steps:
      - name: Checkout zeroth
        uses: actions/checkout@v4

      - name: zeroth@dojo
        uses: Malstrom/giskard@main
        with:
          repo: .
          mode: zeroth
          framework: dojo
          github-token: ${{ secrets.GITHUB_TOKEN }}

  zeroth-aurora:
    name: zeroth@aurora
    runs-on: ubuntu-latest

    steps:
      - name: Checkout zeroth
        uses: actions/checkout@v4

      - name: zeroth@aurora
        uses: Malstrom/giskard@main
        with:
          repo: .
          mode: zeroth
          framework: aurora
          github-token: ${{ secrets.GITHUB_TOKEN }}
